name: Deploy FastAPI to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.5'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Projet 7 - Réalisez une analyse de sentiments grâce au Deep Learning\prototype\api\requirements.txt

    - name: Run tests
      run: |
        pytest

    - name: Deploy to remote server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          mkdir -p /home/Ethan/AirParadis
          cp -r $GITHUB_WORKSPACE/* /home/Ethan/AirParadis/
          cd /home/Ethan/AirParadis
          git pull origin main
          sudo systemctl restart p7.service
